# Generated by Django 5.2.3 on 2025-07-03 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sname', models.CharField(max_length=30)),
                ('srollno', models.IntegerField()),
                ('smarks', models.IntegerField()),
                ('semial', models.EmailField(max_length=254)),
                ('saddress', models.CharField(max_length=50)),
            ],
        ),
    ]
