# Generated by Django 5.2.1 on 2025-05-30 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empno', models.IntegerField()),
                ('ename', models.CharField(max_length=128)),
                ('job', models.CharField(max_length=128)),
                ('sal', models.FloatField(max_length=128)),
            ],
        ),
    ]
